using System;
using System.Collections.Generic;

namespace EHD.Model.Entity {
    [Serializable]
    public class ChiropracticDetail : EntityBase, IComparable<ChiropracticDetail>, ITreatmentDetail {

        public virtual InitialTreatment InitialTreatment { get; set; }
        public virtual Diagram ChiropracticDiagram { get; set; }
        public virtual string ChiefComplaint { get; set; }
        public virtual string HistoryOfCondition { get; set; }
        public virtual string AggravatingFactors { get; set; }
        public virtual string AssociatedSymptoms { get; set; }
        public virtual string RelievingFactors { get; set; }
        public virtual string PreviousTX { get; set; }
        public virtual string Medical { get; set; }
        public virtual string FamilyHistory { get; set; }
        public virtual string LifeStyle { get; set; }
        public virtual string PastIllness { get; set; }
        public virtual int NumOfCareGiverNeeded { get; set; }
        public virtual string Employer { get; set; }
        public virtual DateTime? LastWorkDate { get; set; }
        public virtual string JobTitleAndDuties { get; set; }
        public virtual string Education { get; set; }
        public virtual DominantHand DominantHand { get; set; }
        public virtual LeftRight ShoulderYergason { get; set; }
        public virtual LeftRight ShoulderSpeed { get; set; }
        public virtual LeftRight ShoulderDropArm { get; set; }
        public virtual LeftRight ShoulderEmptyCan { get; set; }
        public virtual LeftRight ShoulderOBrien { get; set; }
        public virtual LeftRight ShoulderNeerImpingement { get; set; }
        public virtual LeftRight ShoulderKennedyHawkins { get; set; }
        public virtual LeftRight ShoulderHornblower { get; set; }
        public virtual LeftRight ShoulderLiftOff { get; set; }
        public virtual LeftRight ShoulderAnteriorSlide { get; set; }
        public virtual LeftRight ShoulderLoadShift { get; set; }
        public virtual LeftRight ShoulderCrank { get; set; }
        public virtual LeftRight ShoulderAnteriorApprehension { get; set; }
        public virtual LeftRight ShoulderJobeRelocation { get; set; }
        public virtual LeftRight ShoulderPosteriorApprehension { get; set; }
        public virtual LeftRight ShoulderSupraspinatus { get; set; }
        public virtual LeftRight ShoulderInfraspinatus { get; set; }
        public virtual LeftRight ShoulderTeresMinor { get; set; }
        public virtual LeftRight ShoulderTeresMajor { get; set; }
        public virtual LeftRight ShoulderSubscapularis { get; set; }
        public virtual LeftRight ElbowVarusStress { get; set; }
        public virtual LeftRight ElbowVargusStress { get; set; }
        public virtual LeftRight ElbowCozen { get; set; }
        public virtual LeftRight ElbowMill { get; set; }
        public virtual LeftRight ElbowGolferElbow { get; set; }
        public virtual LeftRight ElbowMedianNerveResistedPronationEX { get; set; }
        public virtual LeftRight ElbowMedianNerveResistedFLSupination { get; set; }
        public virtual LeftRight ElbowMedianNerveResistedFLofPIP { get; set; }
        public virtual LeftRight ElbowAINResistedPronationFL { get; set; }
        public virtual LeftRight ElbowRadialNerveResistedSupination { get; set; }
        public virtual LeftRight ElbowRadialNerveResistedEXofThirdFinger { get; set; }
        public virtual LeftRight ElbowUlnarNerveTinelElbow { get; set; }
        public virtual LeftRight ElbowUlnarNerveFullElbowFL { get; set; }
        public virtual LeftRight WristHandFinkelstein { get; set; }
        public virtual LeftRight WristHandFroment { get; set; }
        public virtual LeftRight WristHandPinchGrip { get; set; }
        public virtual LeftRight WristHandPhalen { get; set; }
        public virtual LeftRight WristHandReversePhalen { get; set; }
        public virtual LeftRight WristHandTinelAtWrist { get; set; }
        public virtual LeftRight WristHandAllen { get; set; }
        public virtual LeftRight WristHandBunnelLittler { get; set; }
        public virtual LeftRight WristHandGripStrength { get; set; }
        public virtual LeftRight WristHandPinchStrength { get; set; }
        public virtual LeftRight HipTrueLegLength { get; set; }
        public virtual LeftRight HipApparentLegLength { get; set; }
        public virtual LeftRight HipSLR { get; set; }
        public virtual LeftRight HipThomas { get; set; }
        public virtual LeftRight HipPatrickFabers { get; set; }
        public virtual LeftRight HipAPSICompression { get; set; }
        public virtual LeftRight HipGaenslen { get; set; }
        public virtual LeftRight HipNobelCompression { get; set; }
        public virtual LeftRight HipPsoasStrength { get; set; }
        public virtual LeftRight HipOber { get; set; }
        public virtual LeftRight HipEly { get; set; }
        public virtual LeftRight HipYeoman { get; set; }
        public virtual LeftRight HipHibb { get; set; }
        public virtual LeftRight HipPASICompression { get; set; }
        public virtual LeftRight HipTrendelenburg { get; set; }
        public virtual LeftRight HipOrtolani { get; set; }
        public virtual LeftRight HipBarlow { get; set; }
        public virtual LeftRight HipGaleazziSign { get; set; }
        public virtual LeftRight HipTelescoping { get; set; }
        public virtual LeftRight KneeThessaly { get; set; }
        public virtual LeftRight KneeApleyCompression { get; set; }
        public virtual LeftRight KneeApleyDistraction { get; set; }
        public virtual LeftRight KneePatellarPosition { get; set; }
        public virtual LeftRight KneeWipeTest { get; set; }
        public virtual LeftRight KneeVarusStress { get; set; }
        public virtual LeftRight KneeValgusStress { get; set; }
        public virtual LeftRight KneePosteriorSagSign { get; set; }
        public virtual LeftRight KneeAnteriorDrawer { get; set; }
        public virtual LeftRight KneePosteriorDrawer { get; set; }
        public virtual LeftRight KneeSlocumIR { get; set; }
        public virtual LeftRight KneeSlocumER { get; set; }
        public virtual LeftRight KneeLachman { get; set; }
        public virtual LeftRight KneeLateralPivotShift { get; set; }
        public virtual LeftRight KneeReversePivotShift { get; set; }
        public virtual LeftRight KneeNobelCompression { get; set; }
        public virtual LeftRight KneeHyperextension { get; set; }
        public virtual LeftRight KneeBounceHome { get; set; }
        public virtual LeftRight KneeJointLineTenderness { get; set; }
        public virtual LeftRight KneeMcMurray { get; set; }
        public virtual LeftRight KneeAnderson { get; set; }
        public virtual LeftRight KneePatellarCompression { get; set; }
        public virtual LeftRight KneePatellarApprehension { get; set; }
        public virtual LeftRight KneeClarkeSign { get; set; }
        public virtual LeftRight KneeHughstonPlica { get; set; }
        public virtual LeftRight KneeMediopatellarPlica { get; set; }
        public virtual LeftRight FootAnkleAnteriorDrawer { get; set; }
        public virtual LeftRight FootAnklePosteriorDrawer { get; set; }
        public virtual LeftRight FootAnkleInversionStress1 { get; set; }
        public virtual LeftRight FootAnkleEversionStress1 { get; set; }
        public virtual LeftRight FootAnkleForefootAbduction { get; set; }
        public virtual LeftRight FootAnkleExternalRotation { get; set; }
        public virtual LeftRight FootAnkleSyndesmosisSqueeze { get; set; }
        public virtual LeftRight FootAnkleForefootNeuromaSqueeze { get; set; }
        public virtual LeftRight FootAnklePlanarFasciaTenderness { get; set; }
        public virtual LeftRight FootAnkleHoman { get; set; }
        public virtual LeftRight FootAnkleThompson { get; set; }
        public virtual LeftRight FootAnkleValgusStress { get; set; }
        public virtual LeftRight FootAnkleVarusStress { get; set; }
        public virtual LeftRight FootAnkleATFL { get; set; }
        public virtual LeftRight FootAnkleCFL { get; set; }
        public virtual LeftRight FootAnkleInversionStress2 { get; set; }
        public virtual LeftRight FootAnkleEversionStress2 { get; set; }
        public virtual LeftRight OtherTMJ { get; set; }
        public virtual LeftRight OtherGAIT { get; set; }
        public virtual LeftRight OtherBloodPressure { get; set; }
        public virtual LeftRight OtherHeartRate { get; set; }
        public virtual LeftRight OtherPulse { get; set; }
        public virtual LeftRight MyotomesC2 { get; set; }
        public virtual LeftRight MyotomesC3 { get; set; }
        public virtual LeftRight MyotomesC4 { get; set; }
        public virtual LeftRight MyotomesC5 { get; set; }
        public virtual LeftRight MyotomesC6 { get; set; }
        public virtual LeftRight MyotomesC7 { get; set; }
        public virtual LeftRight MyotomesC8 { get; set; }
        public virtual LeftRight MyotomesT1 { get; set; }
        public virtual LeftRight MyotomesL2 { get; set; }
        public virtual LeftRight MyotomesL3 { get; set; }
        public virtual LeftRight MyotomesL4 { get; set; }
        public virtual LeftRight MyotomesS1 { get; set; }
        public virtual LeftRight MyotomesS2 { get; set; }
        public virtual LeftRight MyotomesS4 { get; set; }
        public virtual LeftRight DermatomesC4 { get; set; }
        public virtual LeftRight DermatomesC5 { get; set; }
        public virtual LeftRight DermatomesC6 { get; set; }
        public virtual LeftRight DermatomesC7 { get; set; }
        public virtual LeftRight DermatomesC8 { get; set; }
        public virtual LeftRight DermatomesT1 { get; set; }
        public virtual LeftRight DermatomesT2 { get; set; }
        public virtual LeftRight DermatomesL3 { get; set; }
        public virtual LeftRight DermatomesL4 { get; set; }
        public virtual LeftRight DermatomesL5LateralFoot { get; set; }
        public virtual LeftRight DermatomesS1 { get; set; }
        public virtual LeftRight DermatomesL5AnteriorLeg { get; set; }
        public virtual LeftRight DermatomesS2 { get; set; }
        public virtual LeftRight DeepTendonReflexesC5 { get; set; }
        public virtual LeftRight DeepTendonReflexesC6 { get; set; }
        public virtual LeftRight DeepTendonReflexesC7 { get; set; }
        public virtual LeftRight DeepTendonReflexesL4 { get; set; }
        public virtual LeftRight DeepTendonReflexesS1 { get; set; }
        public virtual bool CranialNerveExamCN1OlfactoryCoffee { get; set; }
        public virtual bool CranialNerveExamCN1OlfactoryVanilla { get; set; }
        public virtual bool CranialNerveExamCN1OlfactoryOrange { get; set; }
        public virtual string CranialNerveExamCN2 { get; set; }
        public virtual string CranialNerveExamCN346 { get; set; }
        public virtual string CranialNerveExamCN7 { get; set; }
        public virtual string CranialNerveExamCN11 { get; set; }
        public virtual string CranialNerveExamCN12 { get; set; }
        public virtual string SystemsReview { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalValsalva { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalKemp { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalSpurling { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalJackson { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalDoorbell { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalSotoHall { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalKernig { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalHermitte { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalEAST { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalAdson { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalWrightHyperabduction { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalEden { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalRotaryChair { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalDixHallpike { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalSubOccipitals { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalTrapezius { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalLevatorScapulae { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalErectors { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalSternocleidomastoid { get; set; }
        public virtual LeftRight OrthopaedicExamSpineCervicalScalenes { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicValsalva { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicChestExpansion { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicScapularApproximation { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicT1NerveStretch { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicT2NerveStretch { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicSlumpTest { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicSotoHall { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicSternalCompression { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicAbdominalReflex { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicBeevorSign { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicSLR { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicTrueLegLength { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicHermitte { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicKernig { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicRhomboids { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicTrapezius { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicErectors { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicLatissimus { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicSerratusPostInf { get; set; }
        public virtual LeftRight OrthopaedicExamSpineThoracicPcMajorMinor { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarValsalva { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarKemp { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarSLR { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarBraggards { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarBowstring { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarPatrickFaber { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarThomas { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarAPSICompression { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarPPPP { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarPASICompression { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarEly { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarYeoman { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarHibbs { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarErectors { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarGluteusMax { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarGluteusMedMin { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarPiriformis { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarPsoas { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarTFLITB { get; set; }
        public virtual LeftRight OrthopaedicExamSpineLumbarQuadratusLumborum { get; set; }
        public virtual int OrthopaedicExamCervicalFlexionROM { get; set; }
        public virtual int OrthopaedicExamCervicalFlexionERP { get; set; }
        public virtual string OrthopaedicExamCervicalFlexionComment { get; set; }
        public virtual int OrthopaedicExamCervicalExtensionROM { get; set; }
        public virtual int OrthopaedicExamCervicalExtensionERP { get; set; }
        public virtual string OrthopaedicExamCervicalExtensionComment { get; set; }
        public virtual int OrthopaedicExamCervicalRightRotationROM { get; set; }
        public virtual int OrthopaedicExamCervicalRightRotationERP { get; set; }
        public virtual string OrthopaedicExamCervicalRightRotationComment { get; set; }
        public virtual int OrthopaedicExamCervicalLeftRotationROM { get; set; }
        public virtual int OrthopaedicExamCervicalLeftRotationERP { get; set; }
        public virtual string OrthopaedicExamCervicalLeftRotationComment { get; set; }
        public virtual int OrthopaedicExamCervicalRightLateralFlexionROM { get; set; }
        public virtual int OrthopaedicExamCervicalRightLateralFlexionERP { get; set; }
        public virtual string OrthopaedicExamCervicalRightLateralFlexionComment { get; set; }
        public virtual int OrthopaedicExamCervicalLeftLateralFlexionROM { get; set; }
        public virtual int OrthopaedicExamCervicalLeftLateralFlexionERP { get; set; }
        public virtual string OrthopaedicExamCervicalLeftLateralFlexionComment { get; set; }
        public virtual int OrthopaedicExamShoulderRightFlexionROM { get; set; }
        public virtual int OrthopaedicExamShoulderRightFlexionERP { get; set; }
        public virtual string OrthopaedicExamShoulderRightFlexionComment { get; set; }
        public virtual int OrthopaedicExamShoulderLeftFlexionROM { get; set; }
        public virtual int OrthopaedicExamShoulderLeftFlexionERP { get; set; }
        public virtual string OrthopaedicExamShoulderLeftFlexionComment { get; set; }
        public virtual int OrthopaedicExamShoulderRightAbductionROM { get; set; }
        public virtual int OrthopaedicExamShoulderRightAbductionERP { get; set; }
        public virtual string OrthopaedicExamShoulderRightAbductionComment { get; set; }
        public virtual int OrthopaedicExamShoulderLeftAbductionROM { get; set; }
        public virtual int OrthopaedicExamShoulderLeftAbductionERP { get; set; }
        public virtual string OrthopaedicExamShoulderLeftAbductionComment { get; set; }
        public virtual int OrthopaedicExamShoulderRightInternalRotationROM { get; set; }
        public virtual int OrthopaedicExamShoulderRightInternalRotationERP { get; set; }
        public virtual string OrthopaedicExamShoulderRightInternalRotationComment { get; set; }
        public virtual int OrthopaedicExamShoulderLeftInternalRotationROM { get; set; }
        public virtual int OrthopaedicExamShoulderLeftInternalRotationERP { get; set; }
        public virtual string OrthopaedicExamShoulderLeftInternalRotationComment { get; set; }
        public virtual int OrthopaedicExamShoulderRightExternalRotationROM { get; set; }
        public virtual int OrthopaedicExamShoulderRightExternalRotationERP { get; set; }
        public virtual string OrthopaedicExamShoulderRightExternalRotationComment { get; set; }
        public virtual int OrthopaedicExamShoulderLeftExternalRotationROM { get; set; }
        public virtual int OrthopaedicExamShoulderLeftExternalRotationERP { get; set; }
        public virtual string OrthopaedicExamShoulderLeftExternalRotationComment { get; set; }
        public virtual int OrthopaedicExamLumbarFlexionROM { get; set; }
        public virtual int OrthopaedicExamLumbarFlexionERP { get; set; }
        public virtual string OrthopaedicExamLumbarFlexionComment { get; set; }
        public virtual int OrthopaedicExamLumbarExtensionROM { get; set; }
        public virtual int OrthopaedicExamLumbarExtensionERP { get; set; }
        public virtual string OrthopaedicExamLumbarExtensionComment { get; set; }
        public virtual int OrthopaedicExamLumbarRightLateralFlexionROM { get; set; }
        public virtual int OrthopaedicExamLumbarRightLateralFlexionERP { get; set; }
        public virtual string OrthopaedicExamLumbarRightLateralFlexionComment { get; set; }
        public virtual int OrthopaedicExamLumbarLeftLateralFlexionROM { get; set; }
        public virtual int OrthopaedicExamLumbarLeftLateralFlexionERP { get; set; }
        public virtual string OrthopaedicExamLumbarLeftLateralFlexionComment { get; set; }
        public virtual int OrthopaedicExamLumbarRightRotationROM { get; set; }
        public virtual int OrthopaedicExamLumbarRightRotationERP { get; set; }
        public virtual string OrthopaedicExamLumbarRightRotationComment { get; set; }
        public virtual int OrthopaedicExamLumbarLeftRotationROM { get; set; }
        public virtual int OrthopaedicExamLumbarLeftRotationERP { get; set; }
        public virtual string OrthopaedicExamLumbarLeftRotationComment { get; set; }
        public virtual int OrthopaedicExamElbowRightFlexionROM { get; set; }
        public virtual int OrthopaedicExamElbowRightFlexionERP { get; set; }
        public virtual string OrthopaedicExamElbowRightFlexionComment { get; set; }
        public virtual int OrthopaedicExamElbowLeftFlexionROM { get; set; }
        public virtual int OrthopaedicExamElbowLeftFlexionERP { get; set; }
        public virtual string OrthopaedicExamElbowLeftFlexionComment { get; set; }
        public virtual int OrthopaedicExamElbowRightExtensionROM { get; set; }
        public virtual int OrthopaedicExamElbowRightExtensionERP { get; set; }
        public virtual string OrthopaedicExamElbowRightExtensionComment { get; set; }
        public virtual int OrthopaedicExamElbowLeftExtensionROM { get; set; }
        public virtual int OrthopaedicExamElbowLeftExtensionERP { get; set; }
        public virtual string OrthopaedicExamElbowLeftExtensionComment { get; set; }
        public virtual int OrthopaedicExamHipRightFlexionROM { get; set; }
        public virtual int OrthopaedicExamHipRightFlexionERP { get; set; }
        public virtual string OrthopaedicExamHipRightFlexionComment { get; set; }
        public virtual int OrthopaedicExamHipLeftFlexionROM { get; set; }
        public virtual int OrthopaedicExamHipLeftFlexionERP { get; set; }
        public virtual string OrthopaedicExamHipLeftFlexionComment { get; set; }
        public virtual int OrthopaedicExamHipRightExtensionROM { get; set; }
        public virtual int OrthopaedicExamHipRightExtensionERP { get; set; }
        public virtual string OrthopaedicExamHipRightExtensionComment { get; set; }
        public virtual int OrthopaedicExamHipLeftExtensionROM { get; set; }
        public virtual int OrthopaedicExamHipLeftExtensionERP { get; set; }
        public virtual string OrthopaedicExamHipLeftExtensionComment { get; set; }
        public virtual int OrthopaedicExamHipRightAbductionROM { get; set; }
        public virtual int OrthopaedicExamHipRightAbductionERP { get; set; }
        public virtual string OrthopaedicExamHipRightAbductionComment { get; set; }
        public virtual int OrthopaedicExamHipLeftAbductionROM { get; set; }
        public virtual int OrthopaedicExamHipLeftAbductionERP { get; set; }
        public virtual string OrthopaedicExamHipLeftAbductionComment { get; set; }
        public virtual int OrthopaedicExamHipRightInternalRotationROM { get; set; }
        public virtual int OrthopaedicExamHipRightInternalRotationERP { get; set; }
        public virtual string OrthopaedicExamHipRightInternalRotationComment { get; set; }
        public virtual int OrthopaedicExamHipLeftInternalRotationROM { get; set; }
        public virtual int OrthopaedicExamHipLeftInternalRotationERP { get; set; }
        public virtual string OrthopaedicExamHipLeftInternalRotationComment { get; set; }
        public virtual int OrthopaedicExamHipRightExternalRotationROM { get; set; }
        public virtual int OrthopaedicExamHipRightExternalRotationERP { get; set; }
        public virtual string OrthopaedicExamHipRightExternalRotationComment { get; set; }
        public virtual int OrthopaedicExamHipLeftExternalRotationROM { get; set; }
        public virtual int OrthopaedicExamHipLeftExternalRotationERP { get; set; }
        public virtual string OrthopaedicExamHipLeftExternalRotationComment { get; set; }
        public virtual int OrthopaedicExamWristRightFlexionROM { get; set; }
        public virtual int OrthopaedicExamWristRightFlexionERP { get; set; }
        public virtual string OrthopaedicExamWristRightFlexionComment { get; set; }
        public virtual int OrthopaedicExamWristLeftFlexionROM { get; set; }
        public virtual int OrthopaedicExamWristLeftFlexionERP { get; set; }
        public virtual string OrthopaedicExamWristLeftFlexionComment { get; set; }
        public virtual int OrthopaedicExamWristRightExtensionROM { get; set; }
        public virtual int OrthopaedicExamWristRightExtensionERP { get; set; }
        public virtual string OrthopaedicExamWristRightExtensionComment { get; set; }
        public virtual int OrthopaedicExamWristLeftExtensionROM { get; set; }
        public virtual int OrthopaedicExamWristLeftExtensionERP { get; set; }
        public virtual string OrthopaedicExamWristLeftExtensionComment { get; set; }
        public virtual int OrthopaedicExamWristRightRadialDeviationROM { get; set; }
        public virtual int OrthopaedicExamWristRightRadialDeviationERP { get; set; }
        public virtual string OrthopaedicExamWristRightRadialDeviationComment { get; set; }
        public virtual int OrthopaedicExamWristLeftRadialDeviationROM { get; set; }
        public virtual int OrthopaedicExamWristLeftRadialDeviationERP { get; set; }
        public virtual string OrthopaedicExamWristLeftRadialDeviationComment { get; set; }
        public virtual int OrthopaedicExamWristRightUlnarDeviationROM { get; set; }
        public virtual int OrthopaedicExamWristRightUlnarDeviationERP { get; set; }
        public virtual string OrthopaedicExamWristRightUlnarDeviationComment { get; set; }
        public virtual int OrthopaedicExamWristLeftUlnarDeviationROM { get; set; }
        public virtual int OrthopaedicExamWristLeftUlnarDeviationERP { get; set; }
        public virtual string OrthopaedicExamWristLeftUlnarDeviationComment { get; set; }
        public virtual int OrthopaedicExamKneeRightFlexionROM { get; set; }
        public virtual int OrthopaedicExamKneeRightFlexionERP { get; set; }
        public virtual string OrthopaedicExamKneeRightFlexionComment { get; set; }
        public virtual int OrthopaedicExamKneeLeftFlexionROM { get; set; }
        public virtual int OrthopaedicExamKneeLeftFlexionERP { get; set; }
        public virtual string OrthopaedicExamKneeLeftFlexionComment { get; set; }
        public virtual int OrthopaedicExamKneeRightExtensionROM { get; set; }
        public virtual int OrthopaedicExamKneeRightExtensionERP { get; set; }
        public virtual string OrthopaedicExamKneeRightExtensionComment { get; set; }
        public virtual int OrthopaedicExamKneeLeftExtensionROM { get; set; }
        public virtual int OrthopaedicExamKneeLeftExtensionERP { get; set; }
        public virtual string OrthopaedicExamKneeLeftExtensionComment { get; set; }
        public virtual int OrthopaedicExamKneeSquatROM { get; set; }
        public virtual int OrthopaedicExamKneeSquatERP { get; set; }
        public virtual string OrthopaedicExamKneeSquatComment { get; set; }
        public virtual int OrthopaedicExamAnkleRightDorsiflexionROM { get; set; }
        public virtual int OrthopaedicExamAnkleRightDorsiflexionERP { get; set; }
        public virtual string OrthopaedicExamAnkleRightDorsiflexionComment { get; set; }
        public virtual int OrthopaedicExamAnkleLeftDorsiflexionROM { get; set; }
        public virtual int OrthopaedicExamAnkleLeftDorsiflexionERP { get; set; }
        public virtual string OrthopaedicExamAnkleLeftDorsiflexionComment { get; set; }
        public virtual int OrthopaedicExamAnkleRightPlantarFlexionROM { get; set; }
        public virtual int OrthopaedicExamAnkleRightPlantarFlexionERP { get; set; }
        public virtual string OrthopaedicExamAnkleRightPlantarFlexionComment { get; set; }
        public virtual int OrthopaedicExamAnkleLeftPlantarFlexionROM { get; set; }
        public virtual int OrthopaedicExamAnkleLeftPlantarFlexionERP { get; set; }
        public virtual string OrthopaedicExamAnkleLeftPlantarFlexionComment { get; set; }
        public virtual int OrthopaedicExamAnkleRightInversionROM { get; set; }
        public virtual int OrthopaedicExamAnkleRightInversionERP { get; set; }
        public virtual string OrthopaedicExamAnkleRightInversionComment { get; set; }
        public virtual int OrthopaedicExamAnkleLeftInversionROM { get; set; }
        public virtual int OrthopaedicExamAnkleLeftInversionERP { get; set; }
        public virtual string OrthopaedicExamAnkleLeftInversionComment { get; set; }
        public virtual int OrthopaedicExamAnkleRightEversionROM { get; set; }
        public virtual int OrthopaedicExamAnkleRightEversionERP { get; set; }
        public virtual string OrthopaedicExamAnkleRightEversionComment { get; set; }
        public virtual int OrthopaedicExamAnkleLeftEversionROM { get; set; }
        public virtual int OrthopaedicExamAnkleLeftEversionERP { get; set; }
        public virtual string OrthopaedicExamAnkleLeftEversionComment { get; set; }
        public virtual string ChiropracticDiagramNote { get; set; }
        public virtual bool FlagSeverityOfSpecificSymptoms { get; set; }
        public virtual bool FlagEmergenceOfRadicularIrritation { get; set; }
        public virtual bool FlagPreviousHistoryOfHeadInjury { get; set; }
        public virtual bool FlagPreExistAutoimmuneDisease { get; set; }
        public virtual bool FlagSystemicOrChronicDiseasePresent { get; set; }
        public virtual bool FlagSignificantRecentWeightLossGain { get; set; }
        public virtual bool FlagOlderAge { get; set; }
        public virtual bool FlagPriorHistoryOfPsychologicalDisturbance { get; set; }
        public virtual bool FlagPregnancy { get; set; }
        public virtual bool FlagFeverChills { get; set; }
        public virtual bool FlagRecentInfection { get; set; }
        public virtual string FlagOther { get; set; }
        public virtual bool FlagHeadRotatedOutOfPosition { get; set; }
        public virtual bool FlagMultipleImpact { get; set; }
        public virtual bool FlagShowingSignsOfPTS { get; set; }
        public virtual string Diagnosis { get; set; }
        public virtual string Recommendations { get; set; }


        public override string ToString() {
            return base.ToString();
        }

        public virtual int CompareTo(ChiropracticDetail other) {
            if(other == null) return 0;

            return this.DisplayName.CompareTo(other.DisplayName);
        }
    }

}
